### ISSUE TITLE
No conversation state found in session

### ISSUE THREAD

**Issue by C4n4rd0** [Unicon/shib-cas-authn3#11]
I'm working with Shibboleth IDP 3.1.2 and CAS 4.0. My goal is to integrate the shibboleth IDP with CAS to get SAML 2.0 support.
I've installed Shibboleth IDP 3.1.2 on a tomcat server. I've installed CAS 4.0 on an other tomcat server. And I installed shib-cas-authn3 using the installation guide on the idp tomcat server.

Here is the scenario:

1) Go to http://shibboleth_idp_server:8080/idp/profile/cas/login?service=http://whatever_url.com

```
Expected Result: Redirect (302) to http://cas_server:8080/cas/login?service=http%3A%2F%2Fshibboleth_idp_server%3A8080%2Fidp%2FAuthn%2FExtCas%3Fconversation%3De1s1&entityId=http%3A%2F%2Fwhatever_url.com
        CAS display the login page

Obtained Result: Redirect (302) to http://cas_server:8080/cas/login?service=http%3A%2F%2Fshibboleth_idp_server%3A8080%2Fidp%2FAuthn%2FExtCas%3Fconversation%3De1s1&entityId=http%3A%2F%2Fwhatever_url.com
        CAS display the login page
```

2) Fill login/password and validate

```
Expected Result: CAS generate a service ticket and redirect to http://shibboleth_idp_server:8080/idp/Authn/ExtCas?conversation=e1s1&entityId=http://whatever_url.com&ticket=ST-XXXXXXXXXXXXXXXXXX
                 Then ShibcasAuthServlet should call service validate on the CAS server.

Obtained Result: CAS generate a service ticket and redirect to http://shibboleth_idp_server:8080/idp/Authn/ExtCas?conversation=e1s1&ticket=ST-XXXXXXXXXXXXXXXXXX
                 And ends with the http error 500 with the following stack trace:

                 HTTP Status 500 - Error processing ShibCas authentication request

                type Exception report

                message Error processing ShibCas authentication request

                description The server encountered an internal error that prevented it from fulfilling this request.

                exception

                javax.servlet.ServletException: Error processing ShibCas authentication request
                    net.unicon.idp.externalauth.ShibcasAuthServlet.doGet(ShibcasAuthServlet.java:152)
                    javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
                    javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
                    net.shibboleth.idp.log.SLF4JMDCServletFilter.doFilter(SLF4JMDCServletFilter.java:64)
                    net.shibboleth.utilities.java.support.net.RequestResponseContextFilter.doFilter(RequestResponseContextFilter.java:60)
                    org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
                    org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                root cause

                net.shibboleth.idp.authn.ExternalAuthenticationException: No conversation state found in session
                    net.shibboleth.idp.authn.ExternalAuthentication.startExternalAuthentication(ExternalAuthentication.java:89)
                    net.unicon.idp.externalauth.ShibcasAuthServlet.doGet(ShibcasAuthServlet.java:113)
                    javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
                    javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
                    net.shibboleth.idp.log.SLF4JMDCServletFilter.doFilter(SLF4JMDCServletFilter.java:64)
                    net.shibboleth.utilities.java.support.net.RequestResponseContextFilter.doFilter(RequestResponseContextFilter.java:60)
                    org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
                    org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

                Here is the idp-proceed log:

                    2015-08-27 16:01:26,884 - INFO [net.shibboleth.utilities.java.support.security.BasicKeystoreKeyStrategy:327] - Default key version has not changed, still secret1
                    2015-08-27 16:09:46,156 - DEBUG [net.shibboleth.idp.session.impl.PopulateSessionContext:131] - Profile Action PopulateSessionContext: No session found for client
                    2015-08-27 16:09:46,157 - DEBUG [net.shibboleth.idp.cas.service.PatternServiceRegistry:60] - Evaluating whether http://success_url.com matches http://*
                    2015-08-27 16:09:46,157 - DEBUG [net.shibboleth.idp.cas.flow.BuildRelyingPartyContextAction:86] - Setting up RP context for unverified relying party http://success_url.com
                    2015-08-27 16:09:46,216 - DEBUG [net.shibboleth.idp.relyingparty.impl.DefaultRelyingPartyConfigurationResolver:284] - Resolving relying party configuration
                    2015-08-27 16:09:46,217 - DEBUG [net.shibboleth.idp.relyingparty.impl.DefaultRelyingPartyConfigurationResolver:290] - Profile request is unverified, returning configuration shibboleth.UnverifiedRelyingParty
                    2015-08-27 16:09:46,217 - DEBUG [net.shibboleth.idp.profile.impl.SelectRelyingPartyConfiguration:136] - Profile Action SelectRelyingPartyConfiguration: Found relying party configuration shibboleth.UnverifiedRelyingParty for request
                    2015-08-27 16:09:46,218 - DEBUG [net.shibboleth.idp.cas.flow.CheckAuthenticationRequiredAction:82] - IdP session not found
                    2015-08-27 16:09:46,220 - DEBUG [net.shibboleth.idp.authn.impl.PopulateAuthenticationContext:125] - Profile Action PopulateAuthenticationContext: Installing custom PrincipalEvalPredicateFactoryRegistry into AuthenticationContext
                    2015-08-27 16:09:46,221 - DEBUG [net.shibboleth.idp.authn.impl.PopulateAuthenticationContext:158] - Profile Action PopulateAuthenticationContext: Installed 1 authentication flows into AuthenticationContext
                    2015-08-27 16:09:46,222 - DEBUG [net.shibboleth.idp.session.impl.PopulateSessionContext:131] - Profile Action PopulateSessionContext: No session found for client
                    2015-08-27 16:09:46,223 - DEBUG [net.shibboleth.idp.authn.impl.FilterFlowsByForcedAuthn:53] - Profile Action FilterFlowsByForcedAuthn: Request does not have forced authentication requirement, nothing to do
                    2015-08-27 16:09:46,224 - DEBUG [net.shibboleth.idp.authn.impl.FilterFlowsByPassivity:53] - Profile Action FilterFlowsByPassivity: Request does not have passive requirement, nothing to do
                    2015-08-27 16:09:46,225 - DEBUG [net.shibboleth.idp.authn.impl.FilterFlowsByNonBrowserSupport:53] - Profile Action FilterFlowsByNonBrowserSupport: Request does not have non-browser requirement, nothing to do
                    2015-08-27 16:09:46,226 - DEBUG [net.shibboleth.idp.authn.impl.SelectAuthenticationFlow:241] - Profile Action SelectAuthenticationFlow: No specific Principals requested
                    2015-08-27 16:09:46,227 - DEBUG [net.shibboleth.idp.authn.impl.SelectAuthenticationFlow:267] - Profile Action SelectAuthenticationFlow: No usable active results available, selecting an inactive flow
                    2015-08-27 16:09:46,228 - DEBUG [net.shibboleth.idp.authn.impl.SelectAuthenticationFlow:309] - Profile Action SelectAuthenticationFlow: Selecting inactive authentication flow authn/Shibcas

                Here is the tomcat log:

                    Aug 27, 2015 4:13:55 PM org.apache.catalina.core.StandardWrapperValve invoke
                    SEVERE: Servlet.service() for servlet [ShibCas Auth Servlet] in context with path [/idp] threw exception [Error processing ShibCas authentication request] with root cause
                    net.shibboleth.idp.authn.ExternalAuthenticationException: No conversation state found in session
                            at net.shibboleth.idp.authn.ExternalAuthentication.startExternalAuthentication(ExternalAuthentication.java:89)
                            at net.unicon.idp.externalauth.ShibcasAuthServlet.doGet(ShibcasAuthServlet.java:113)
                            at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
                            at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
                            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
                            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
                            at net.shibboleth.idp.log.SLF4JMDCServletFilter.doFilter(SLF4JMDCServletFilter.java:64)
                            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
                            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
                            at net.shibboleth.utilities.java.support.net.RequestResponseContextFilter.doFilter(RequestResponseContextFilter.java:60)
                            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
                            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
                            at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
                            at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
                            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
                            at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:205)
                            at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
                            at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
                            at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
                            at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
                            at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
                            at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
                            at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
                            at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023)
                            at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
                            at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
                            at java.lang.Thread.run(Thread.java:724)
```

While reading the Shibboleth code, it seems like the conversation id is not setted in the session. Can you explain me why? What did I miss?

Regards

**Comment by mmoayyed** [comment]
Why do you start with?
http://shibboleth_idp_server:8080/idp/profile/cas/login?service=http://whatever_url.com

Aren't you delegating authentication to an external CAS server? If so, why are using IdP's CAS endpoint for a start?

**Comment by mmoayyed** [comment]
Also, running the idp under 8080 may impose issues in the future. 

You should start from your SP.

**Comment by C4n4rd0** [comment]
I start with http://shibboleth_idp_server:8080/idp/profile/cas/login?service=http://whatever_url.com beacause I didn't know what URL to use. So I looked at the web.xml, I found this address and it starts the flow. So, I assumed it's the good URL. But it seems it's not. Right?

I don't really need Shibboleth. The only thing I want, is the SAML 2.0 support for my CAS server. So, the less software I have to install, the better I am. That's why I did'nt installed the Shibboleth SP. What kind of issues, running the idp under 8080 may appears? Isn't it a classic war? Should I run it behind a http server?

A conversation is a spring flow object. When I looked at the stack trace, an exception is thrown in the method ShibcasAuthServlet.doGet() when it calls ExternalAuthentication.startExternalAuthentication(request).
After reading the code of the method ExternalAuthentication.startExternalAuthentication(), it seems that the conversation id is not setted in the session

```
final Object obj = request.getSession().getAttribute(CONVERSATION_KEY + conv);
if (obj == null || !(obj instanceof ExternalAuthentication)) {
throw new ExternalAuthenticationException("No conversation state found in session");
}
```

**Comment by C4n4rd0** [comment]
But I can't see where the plugin do some kind of getSession().setAttribute(CONVERSATION_KEY + conv,obj);

**Comment by iigorr** [comment]
Hi, 

have you been able this issue? We are having exactly the same problem after switching from shibboleth 3.2.0.

After a successful redirect to our CAS and login, on the way back, we are getting the exception:

```
24-Nov-2015 07:12:29.225 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
24-Nov-2015 07:13:33.216 SEVERE [http-nio-8443-exec-7] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [ShibCas Auth Servlet] in context with path [/idp] threw exception [Error processing ShibCas authentication request] with root cause
 net.shibboleth.idp.authn.ExternalAuthenticationException: No conversation state found in session for key (e1s1)
    at net.shibboleth.idp.authn.ExternalAuthentication.startExternalAuthentication(ExternalAuthentication.java:132)
    at net.unicon.idp.externalauth.ShibcasAuthServlet.doGet(ShibcasAuthServlet.java:113)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at net.shibboleth.idp.log.SLF4JMDCServletFilter.doFilter(SLF4JMDCServletFilter.java:72)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at net.shibboleth.utilities.java.support.net.RequestResponseContextFilter.doFilter(RequestResponseContextFilter.java:60)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:203)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
    at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
```

What's wrong here?

**Comment by C4n4rd0** [comment]
Yes I did. It was a cookie issue.

The domain of my cookies was .test.mycompany.com but I was redirected to http://shibboleth_idp_server:8080. It can't work.

To solve this, I had to redirect to http://shibboleth_idp_server.test.mycompany.com:8080

**Comment by siwilkins** [comment]
We are getting a lot of occurrences of this error, particularly integrating Google Apps with our Shibboleth/CAS instance. Our Google Apps session lifetime is set to 12h, and so we think the typical pattern occurs when users leave their machine on and their Google session times-out in the evening, resulting in a redirection to the IDP and in turn CAS; they then come in the next morning, sign-in to CAS and get the error. We've mitigated it slightly by setting the tomcat session.lifetime to 24h, but a) are still getting a lot of occurrences (1000s/day; we're a university so have a lot of users); b) are struggling to control the heap size.

a) is there any better way of mitigating this scenario?
b) one possibility we have thought of, is that if the original service could be passed as an extra GET parameter in the service name to CAS, then on the return journey from CAS our load balancer could pick this up on the IDP when there's a 500 error on the IDP, and redirect back to the service, forcing a second round-trip to the IDP and CAS, thereby successfully logging the user in and avoiding the user ever seeing the error. Is this possible?

**Comment by jtgasper3** [comment]
Hi Si,

The issue is that the authnRequest is stored in the Shibboleth IdP's web/tomcat session. When that ends, because the person sat on the CAS Server's login page too long, when the user does come back the IdP doesn't know what to do with them. It's forgotten. Bumping up the session length is the common fix that a few of our clients have done.

As for scenario `b`, the entityId is sent to CAS Server either as a part of the service url or as a standalone querystring parameter. Either way, sending that back to the IdP doesn't really help. The IdP does not know the invocation url of the SP, it only can determine the ACS url to send the response. If we sent the user to that ACS url with no authnResponse, they are most likely to get error messages on that side.

**Comment by siwilkins** [comment]
Hi John. Thanks very much for your response. That's a shame. We've upp'ed the tomcat timeout to 24h, but still get lots of occurrences, and are now ending up with the heap usage spiralling out of control. We've upped it a few times after the heaps been exhausted, so maybe we just need to increase the tomcat session some more and the heap lots more :-)
